pipeline{
    agent any
    stages{
        stage("BUILD"){            
            tools {
            go 'golang 1.18.1'
            }



            steps{
                echo "======== BUILDING MAIN GO APP ========"
                sh "go build main.go"
                echo "======== BUILDING REDIRECT GO APP ========"
                sh "go build redirecthttp/redirect.go"
            }
        }

        stage("DEPLOY EC2"){
           options {
                timeout(time: 40, unit: "SECONDS")
                 }
            steps{
                sshagent(credentials: ['aws-tarlan-ohio-ubuntu-focal-public','aws-tarlan-ohio-ubuntu-focal-private']) {
                    echo "======== DEPLOYING BINARIES ========"
                    sh '''                    
                        [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                        
                        ssh-keyscan -t rsa,dsa ec2-3-129-209-178.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
                        
                        tar --exclude='./.*' --exclude='./jenkins' --exclude='go.*' -cvzf ./jenkins/artifact.tgz . 
                        
                        scp ./jenkins/* ec2-3-129-209-178.us-east-2.compute.amazonaws.com:/tmp                      
                                                                                                                
                        exec ssh -A ubuntu@ec2-3-129-209-178.us-east-2.compute.amazonaws.com "bash /tmp/bastion.sh &"                       
                                                
                    '''
                }    
            }
        }
    }
}
