pipeline{
    agent any
    stages{
        stage("BUILD"){            
            tools {
            go 'golang 1.18.1'
            }



            steps{
                echo "======== BUILDING MAIN GO APP ========"
                sh "go build main.go"
                echo "======== BUILDING REDIRECT GO APP ========"
                sh "go build redirecthttp/redirect.go"
            }
        }

        stage("DEPLOY EC2"){
            steps{
                sshagent(credentials: ['aws-tarlan-ohio-ubuntu-focal-public','aws-tarlan-ohio-ubuntu-focal-private']) {
                    echo "======== DEPLOYING BINARIES ========"
                    sh '''                    
                        [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                        
                        ssh-keyscan -t rsa,dsa ec2-3-145-168-159.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
                        
                        tar --exclude='./.*' --exclude='./jenkins' --exclude='go.*' -cvzf ./jenkins/artifact.tgz . 
                        
                        scp ./jenkins/* ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com:/tmp                      
                                                                                                                
                        ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com "rm ~/.ssh/known_hosts"
                        
                        for i in `seq 1 2 5`
                          do  
                            ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com 'ssh-keyscan -t rsa,dsa 10.0.${i}.4 >> ~/.ssh/known_hosts'
                            ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com 'scp /tmp/artifact.tgz ubuntu@10.0.${i}.4:/tmp' 
                            ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com 'ssh ubuntu@10.0.${i}.4 "sudo killall main'
                            ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com 'ssh ubuntu@10.0.${i}.4 "tar xvzf /tmp/artifact.tgz --directory /home/ubuntu"'
                            ssh -A ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com 'ssh ubuntu@10.0.${i}.4 "sudo ./main &" &'
                          done              
                    '''
                }    
            }
        }
    }
}
