pipeline{
    agent any
    stages{
        stage("BUILD"){            
            tools {
            go 'golang 1.18.1'
            }



            steps{
                echo "======== BUILDING MAIN GO APP ========"
                sh "go build main.go"
                echo "======== BUILDING REDIRECT GO APP ========"
                sh "go build redirecthttp/redirect.go"
            }
        }

        stage("DEPLOY EC2"){
            steps{
                sshagent(credentials: ['aws-tarlan-ohio-ubuntu-focal-public','aws-tarlan-ohio-ubuntu-focal-private']) {
                    echo "======== DEPLOYING BINARIES ========"
                    sh '''
                        [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                        ssh-keyscan -t rsa,dsa ec2-3-145-168-159.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts  
                        
                        tar --exclude='./idea' --exclude='./jenkins' --exclude='.gitignore' --exclude='go.*' -cvzf artifact.tgz .
                        
                        scp artifact.tgz ubuntu@ec2-3-145-168-159.us-east-2.compute.amazonaws.com:/tmp
                        
                    '''
                }    
            }
        }
    }
}
